spring.datasource.url=${DBU_URL}
spring.datasource.username=${DBU_USERNAME}
spring.datasource.password=${DBU_PASSWORD}

spring.flyway.enabled=false
spring.jpa.hibernate.ddl-auto=none


# Server HTTPS configuration
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD}