spring.datasource.url=jdbc:postgresql://localhost:5432/bank_db
spring.datasource.username=admin
spring.datasource.password=admin123

spring.flyway.enabled=true
spring.flyway.schemas=public
spring.flyway.baselineOnMigrate=true
spring.flyway.locations=classpath:db/migration
spring.jpa.hibernate.ddl-auto=none
