spring.datasource.url=${DBA_URL}
spring.datasource.username=${DBA_USERNAME}
spring.datasource.password=${DBA_PASSWORD}


jwt.secret=${JWTA_SECRET}

spring.flyway.enabled=true
spring.flyway.schemas=public
spring.flyway.baselineOnMigrate=true
spring.flyway.locations=classpath:db/migration
spring.jpa.hibernate.ddl-auto=none
