spring.application.name=fibank

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#JWT Configuration
jwt.secret=jahhdhdyfryryS3445jdhhdhfkfnvjsoeoi9eipglgji43543jdfj
jwt.access.expirationMs=120000
jwt.refresh.expirationMs=604800000 

#Redis configuration
spring.data.redis.host=localhost
spring.data.redis.database=0
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.timeout=6000


# Server HTTPS configuration
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=Hesoiam007
