spring.application.name=fibank

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



spring.profiles.active=prod

#JWT Configuration
jwt.access.expirationMs=120000
jwt.refresh.expirationMs=604800000 

#Redis configuration
spring.data.redis.host=localhost
spring.data.redis.database=0
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.timeout=6000



