CREATE SEQUENCE IF NOT EXISTS auth.role_seq
START WITH 1
INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS auth.roles(
id INT PRIMARY KEY DEFAULT nextval('auth.role_seq'),
name VARCHAR(50) NOT NULL UNIQUE
);